version: '2'
services:
    citytrafficserver-app:
        image: citytrafficserver
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://citytrafficserver-postgresql:5432/cityTrafficServer
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    citytrafficserver-postgresql:
        extends:
            file: postgresql.yml
            service: citytrafficserver-postgresql
